config/routes.rb
# == Route Map
#
#               Prefix Verb   URI Pattern                                         Controller#Action
#             property GET    /properties/:abbreviation(.:format)                 properties#show
#     property_tenants GET    /properties/:property_id/tenants(.:format)          tenants#index
#                      POST   /properties/:property_id/tenants(.:format)          tenants#create
#  new_property_tenant GET    /properties/:property_id/tenants/new(.:format)      tenants#new
# edit_property_tenant GET    /properties/:property_id/tenants/:id/edit(.:format) tenants#edit
#      property_tenant GET    /properties/:property_id/tenants/:id(.:format)      tenants#show
#                      PATCH  /properties/:property_id/tenants/:id(.:format)      tenants#update
#                      PUT    /properties/:property_id/tenants/:id(.:format)      tenants#update
#                      DELETE /properties/:property_id/tenants/:id(.:format)      tenants#destroy
#       property_bills GET    /properties/:property_id/bills(.:format)            bills#index
#                      POST   /properties/:property_id/bills(.:format)            bills#create
#    new_property_bill GET    /properties/:property_id/bills/new(.:format)        bills#new
#   edit_property_bill GET    /properties/:property_id/bills/:id/edit(.:format)   bills#edit
#        property_bill GET    /properties/:property_id/bills/:id(.:format)        bills#show
#                      PATCH  /properties/:property_id/bills/:id(.:format)        bills#update
#                      PUT    /properties/:property_id/bills/:id(.:format)        bills#update
#                      DELETE /properties/:property_id/bills/:id(.:format)        bills#destroy
#           properties GET    /properties(.:format)                               properties#index
#                      POST   /properties(.:format)                               properties#create
#                      PATCH  /properties/:id(.:format)                           properties#update
#                      PUT    /properties/:id(.:format)                           properties#update
#                      DELETE /properties/:id(.:format)                           properties#destroy
#                 root GET    /                                                   properties#index

Rails.application.routes.draw do

  get "properties/:abbreviation", to: "properties#show", as: :property

  resources :properties, except: [:new, :show, :edit] do
    resources :tenants
    resources :bills
  end

  root "properties#index"
end

app/models/tenant.rb
# == Schema Information
#
# Table name: tenants
#
#  id            :integer          not null, primary key
#  move_in_date  :date
#  move_out_date :date
#  name          :string(30)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  property_id   :integer          not null
#
# Indexes
#
#  index_tenants_on_property_id  (property_id)
#
# Foreign Keys
#
#  property_id  (property_id => properties.id)
#
class Tenant < ApplicationRecord
  validates :name, presence: true, length: 2..30
  validates :move_in_date, presence: true
  validates :property_id, presence: true
  validate :move_out_date_is_greater_than_move_in_date

  belongs_to :property

  # Prevent consecutive spaces in tenant names
  def name=(value)
    super(value.squish)
  end

  def move_out_date_is_greater_than_move_in_date
    if move_in_date.present? && move_out_date.present? && move_out_date < move_in_date
      errors.add(:move_out_date, "can't be before move in date")
    end
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]

  # GET /tenants
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  def create
    @tenant = Tenant.new(tenant_params)

    if @tenant.save
      redirect_to @tenant, notice: 'Tenant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tenants/1
  def update
    if @tenant.update(tenant_params)
      redirect_to @tenant, notice: 'Tenant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tenants/1
  def destroy
    @tenant.destroy
    redirect_to tenants_url, notice: 'Tenant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:name, :move_in_date, :move_out_date, :property_id)
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :move_in_date %>
    <%= form.date_select :move_in_date %>
  </div>

  <div class="field">
    <%= form.label :move_out_date %>
    <%= form.date_select :move_out_date %>
  </div>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tenants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Move in date</th>
      <th>Move out date</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tenants.each do |tenant| %>
      <tr>
        <td><%= tenant.name %></td>
        <td><%= tenant.move_in_date %></td>
        <td><%= tenant.move_out_date %></td>
        <td><%= tenant.property_id %></td>
        <td><%= link_to 'Show', tenant %></td>
        <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
        <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New Tenant</h1>

<%= render 'form', tenant: @tenant %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tenant.name %>
</p>

<p>
  <strong>Move in date:</strong>
  <%= @tenant.move_in_date %>
</p>

<p>
  <strong>Move out date:</strong>
  <%= @tenant.move_out_date %>
</p>

<p>
  <strong>Property:</strong>
  <%= @tenant.property_id %>
</p>

<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>