config/routes.rb
# == Route Map
#
#               Prefix Verb   URI Pattern                                         Controller#Action
#             property GET    /properties/:abbreviation(.:format)                 properties#show
#     property_tenants GET    /properties/:property_id/tenants(.:format)          tenants#index
#                      POST   /properties/:property_id/tenants(.:format)          tenants#create
#  new_property_tenant GET    /properties/:property_id/tenants/new(.:format)      tenants#new
# edit_property_tenant GET    /properties/:property_id/tenants/:id/edit(.:format) tenants#edit
#      property_tenant GET    /properties/:property_id/tenants/:id(.:format)      tenants#show
#                      PATCH  /properties/:property_id/tenants/:id(.:format)      tenants#update
#                      PUT    /properties/:property_id/tenants/:id(.:format)      tenants#update
#                      DELETE /properties/:property_id/tenants/:id(.:format)      tenants#destroy
#       property_bills GET    /properties/:property_id/bills(.:format)            bills#index
#                      POST   /properties/:property_id/bills(.:format)            bills#create
#    new_property_bill GET    /properties/:property_id/bills/new(.:format)        bills#new
#   edit_property_bill GET    /properties/:property_id/bills/:id/edit(.:format)   bills#edit
#        property_bill GET    /properties/:property_id/bills/:id(.:format)        bills#show
#                      PATCH  /properties/:property_id/bills/:id(.:format)        bills#update
#                      PUT    /properties/:property_id/bills/:id(.:format)        bills#update
#                      DELETE /properties/:property_id/bills/:id(.:format)        bills#destroy
#           properties GET    /properties(.:format)                               properties#index
#                      POST   /properties(.:format)                               properties#create
#                      PATCH  /properties/:id(.:format)                           properties#update
#                      PUT    /properties/:id(.:format)                           properties#update
#                      DELETE /properties/:id(.:format)                           properties#destroy
#                 root GET    /                                                   properties#index

Rails.application.routes.draw do

  get "properties/:abbreviation", to: "properties#show", as: :property

  resources :properties, except: [:new, :show, :edit] do
    resources :tenants
    resources :bills
  end

  root "properties#index"
end

app/models/bill.rb
# == Schema Information
#
# Table name: bills
#
#  id          :integer          not null, primary key
#  amount      :decimal(8, 2)
#  end_date    :date
#  start_date  :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  property_id :integer          not null
#
# Indexes
#
#  index_bills_on_property_id  (property_id)
#
# Foreign Keys
#
#  property_id  (property_id => properties.id)
#
class Bill < ApplicationRecord
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_is_greater_than_start_date

  belongs_to :property

  def end_date_is_greater_than_start_date
    if start_date.present? && end_date.present? && end_date < start_date
      errors.add(:end_date, "can't be before start date")
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  def create
    @bill = Bill.new(bill_params)

    if @bill.save
      redirect_to @bill, notice: 'Bill was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bills/1
  def update
    if @bill.update(bill_params)
      redirect_to @bill, notice: 'Bill was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bills/1
  def destroy
    @bill.destroy
    redirect_to bills_url, notice: 'Bill was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:start_date, :end_date, :amount, :property_id)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_with(model: bill) do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
        <% bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Amount</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.start_date %></td>
        <td><%= bill.end_date %></td>
        <td><%= bill.amount %></td>
        <td><%= bill.property_id %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<!-- From https://startbootstrap.com/previews/sb-admin-pro -->
<div class="container px-4 mt-4">
  <div class="row">
    <div class="col-lg-8">
      <div class="card mb-4">
        <div class="card-header">
          New Bill
        </div>
        <div class="card-body">
          <!-- TODO -->
          <%= render 'form', bill: @bill %>

          <%= link_to 'Back', bills_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @bill.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @bill.end_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bill.amount %>
</p>

<p>
  <strong>Property:</strong>
  <%= @bill.property_id %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>